In [20]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import googlemaps
import gmplot
import pickle5 as pickle

In [2]:
#google maps API setup
my_key='AIzaSyDHCMCC6zM880H5PnzN8dr7WK8C1Yhbz5s'
gmaps = googlemaps.Client(key=my_key)

In [3]:
class FileProcess(object):#extract data of one day and sort data
    def __init__(self, folder_address):
        self.folder_address =folder_address
    
    def find_dir(self):
        files_name = os.listdir(self.folder_address)
        filesPath = []
        for i in files_name:
            filesPath.append(self.folder_address + i)
        return filesPath
    def DayDataAndDriverID(self,year,month,date): #example: year=2020,month=6,date=20200613
        file_dir= '/Users/liyurun/Downloads/OneDrive_1_11-18-2020/提供データ/配達実績/'+str(year)+'年'+str(month)+'月.xls'
        df = pd.read_excel(file_dir,usecols=[0, 1, 2, 5, 6, 7, 10, 11, 12, 13, 19, 20, 30])
        df_day=df[df['持出日付'] == int(date)]
        day_data = df_day[(df_day['配達乗務員\nコード'] != 0) & (df_day['緯度＿完了優先'] != 0) & (df_day['経度＿完了優先'] != 0)]
        day_data = day_data.reset_index(drop=True)
        day_data = day_data.sort_values(by=['配達乗務員\nコード', '持出時刻', '完了時刻'], axis=0)
        data_grouped = day_data.groupby(by='配達乗務員\nコード')
        driver_id = list(data_grouped.size().index)
        return driver_id,day_data 
    
folder_address='/Users/liyurun/Downloads/OneDrive_1_11-18-2020/提供データ/配達実績/' # folder address
a=FileProcess(folder_address) #define class a
driver_id,day_data=a.DayDataAndDriverID(year=2020,month=6,date=20200613) # extract data of 20200613

In [4]:
day_data

西濃原票№      持出日付    持出時刻   配達社番  配達乗務員\nコード  配達予定時刻  個数    重量  \
106  1360576120  20200613   84500  11956       24089    1020  12   122   
182  2159164823  20200613   84500  11956       24089    1020  15   115   
223  3527829713  20200613   84500  11956       24089    1020  15    72   
69   1133091742  20200613   84600  11956       24089    1100   9    74   
18     45266269  20200613   84600  11956       24089    1120   1    24   
..          ...       ...     ...    ...         ...     ...  ..   ...   
381  8031175257  20200613   90800  39552      861633    1120  40  1000   
736  9319845469  20200613   90800  39552      861633    1120   1     5   
846  9568958971  20200613   90800  39552      861633    1120   1     2   
350  7524646437  20200613   90900  39552      861633    1120   1    27   
7      44264648  20200613  130800  39552      861633    1340   1     2   

         完了日付  完了時刻    緯度＿完了優先     経度＿完了優先       郵便番号  
106  20200613  1029  35.114228  136.640980  5110118.0  
182  20200613  1029  35.114228  136.640980  5110118.0  
223  20200613  1029  35.114228  136.640980  5110118.0  
69   20200613  1042  35.112731  136.639003  5110118.0  
18   20200613  1107  35.107506  136.635094  5110118.0  
..        ...   ...        ...         ...        ...  
381  20200613  1114  35.361501  136.626259  5030893.0  
736  20200613  1114  35.361501  136.626259  5030893.0  
846  20200613  1129  35.362901  136.624016  5030893.0  
350  20200613  1129  35.362901  136.624016  5030893.0  
7    20200613  1314  35.348148  136.638449  5030849.0  

[864 rows x 13 columns]

In [5]:
class DriverInfo(object):# extract any driver's information in this day
    def __init__(self,driver_id,day_data):
        self.day_data=day_data
        self.driver_id=driver_id
        self.number=len(driver_id)
        
    
    def DriverID(self,num):# ID of a driver
        return self.driver_id[num]
    
    def DriverData(self,num):# data of a driver
        return self.day_data[self.day_data['配達乗務員\nコード'] == self.DriverID(num)]
    
    def DeliveryPlace(self,num):# classify delivery (times and positions)
        Data=self.DriverData(num)
        count = 0
        count_mark = []
        temp = Data['完了時刻'].values.tolist()[0]
        for i in range(len(Data['持出時刻'].values.tolist())):
            if Data['持出時刻'].values.tolist()[i] // 100 < temp:
                count_mark.append(count)
            else:
                count += 1
                temp = Data['完了時刻'].values.tolist()[i]
                count_mark.append(count)

        loc_x = []
        loc_y = []
        for i in range(count + 1):
            loc_x.append([])
            loc_y.append([])
            loc_x[i].append(Data['緯度＿完了優先'].values.tolist()[count_mark.index(i)])
            loc_y[i].append(Data['経度＿完了優先'].values.tolist()[count_mark.index(i)])

        for i in range(count + 1):
            if count_mark.count(i) > 1:
                for j in range(count_mark.index(i) + 1, count_mark.index(i) + count_mark.count(i)):
                    if Data['完了時刻'].values.tolist()[j] != Data['完了時刻'].values.tolist()[j - 1]:
                        loc_x[i].append(Data['緯度＿完了優先'].values.tolist()[j])
                        loc_y[i].append(Data['経度＿完了優先'].values.tolist()[j])
        loc = []
        for i in range(count + 1):
            loc.append([])
            for j in range(len(loc_x[i])):
                loc[i].append([])
            for j in range(len(loc_x[i])):
                loc[i][j].append(loc_x[i][j])
                loc[i][j].append(loc_y[i][j])
        return loc
    
    def DeliveryTimes(self,num):#Delivery times in a day
        return len(self.DeliveryPlace(num))
    
    def Location(self,num,Delivery_time):#Delivery location for once delivery time in a day
        return np.array(self.DeliveryPlace(num)[Delivery_time])

In [40]:
class Path(object):# measure the distance between each 2 locations in a set of coordinates
    def __init__(self,coordinates):
        self.coordinates=coordinates
        self.LocationNumbers=len(coordinates)
        
    def RouteDistance(self,origin,destination):# route distance of each 2 locations 
        path=gmaps.directions(origin=origin,destination=destination,mode='driving')
        distance_dict=path[0]['legs'][0]['distance']
        return distance_dict['value']
    
    def RouteDuration(self,origin,destination):# time cost of each 2 locations
        path=gmaps.directions(origin=origin,destination=destination,mode='driving')
        distance_dict=path[0]['legs'][0]['duration']
        
    def RouteSteps(self,origin,destination):# specific route EX. A --> step0 -->step1 -->step3 -->B
        path=gmaps.directions(origin=origin,destination=destination,mode='driving')
        return path[0]['legs'][0]['steps']

    def DistanceMatrix(self):# make distance matrix of a set of locations
        N=len(self.coordinates)
        matrix=[[] for i in range(N)]
        for i in range(N):
            for j in range(N):
                matrix[i].append(self.RouteDistance(self.coordinates[i],self.coordinates[j]))
        return np.array(matrix)


In [41]:
driver_info=DriverInfo(driver_id,day_data)

In [42]:
#Location Matrix Example of the driver[id_index is the last one, first time delivery]
coordinate=driver_info.Location(num=-1,Delivery_time=0)
path_distance=Path(coordinate)
path_distance.DistanceMatrix()

array([[   0,  364,  679,  712,  677, 1025, 1301, 1658, 2121, 1530, 1490,
        1186, 2693, 2673],
       [ 666,    0,  396,  347,  313,  952,  937, 1294, 1757, 1166, 1126,
         822, 2329, 2309],
       [ 201,  833,    0,  796, 1146,  556, 1030, 1038, 2744, 1680, 2666,
        1654, 3191, 3171],
       [1013,  347,  744,    0,  124,  471,  747, 1104, 1567,  976,  936,
         632, 2139, 2119],
       [ 979,  313,  709,  124,    0,  437,  624,  981, 1444,  853,  813,
         509, 2016, 1996],
       [ 615,  979,  707,  471,  437,    0,  570,  578, 1042, 1220, 1524,
         945, 2382, 2362],
       [1089,  937, 1333,  747,  624,  570,    0,  349,  813,  641,  946,
         494, 1804, 1784],
       [1097, 1294, 1690, 1104,  981,  578,  349,    0,  463,  998, 1303,
         850, 2160, 2140],
       [1443, 1629, 2025, 1439, 1316,  924,  684,  702,    0, 1334, 1638,
        1186, 1722, 1702],
       [1739, 1166, 1562,  976,  853, 1220,  641,  998, 1462,    0,  257,
         305, 137

In [9]:
N=len(driver_id) # number of drivers
data_distance=[] #date set
for i in range(N): # for each driver
    data_distance.append([])
    for j in range(driver_info.DeliveryTimes(num=i)):
        data_distance[i].append([])
for i in range(N):
    for j in range(driver_info.DeliveryTimes(num=i)):
        data_distance[i][j].append(driver_info.DriverID(num=i))
        data_distance[i][j].append(j)
        data_distance[i][j].append(driver_info.Location(num=i,Delivery_time=j))
        coordinate=driver_info.Location(num=i,Delivery_time=j)
        path_distance=Path(coordinate)
        path_distance_matrix=path_distance.DistanceMatrix()
        data_distance[i][j].append(path_distance.DistanceMatrix())distance

In [10]:
data_distance

[[[24089,
   0,
   array([[ 35.1142283, 136.6409799],
          [ 35.1127311, 136.6390029],
          [ 35.1075064, 136.6350935],
          [ 35.1003225, 136.6348807]]),
   array([[   0,  343, 1851, 2326],
          [ 343,    0, 1539, 2014],
          [1851, 1539,    0, 2235],
          [2326, 2014, 2235,    0]])]],
 [[26511,
   0,
   array([[ 35.3496094, 136.6077486],
          [ 35.343989 , 136.6090281],
          [ 35.3435914, 136.6073345],
          [ 35.3565137, 136.6041548],
          [ 35.3404848, 136.6007861],
          [ 35.3238542, 136.6128981]]),
   array([[   0,  885,  755,  981, 1691, 4084],
          [ 885,    0,  602, 1720, 1722, 2945],
          [ 755,  602,    0, 1590, 1523, 3356],
          [ 987, 1727, 1597,    0, 2052, 4925],
          [2188, 1660, 1461, 2088,    0, 3087],
          [3559, 2945, 2832, 4394, 3107,    0]])],
  [26511, 1, array([[ 35.3481167, 136.6094797]]), array([[0]])]],
 [[31727,
   0,
   array([[ 35.3537817, 136.6055703],
          [ 35.3550777, 1

In [43]:
# open the 'pkl' file you want to write
output = open('/Users/liyurun/Desktop/distance_data_20200613.pkl', 'wb')
# write the data
pickle.dump(data_distance, output)
output.close()

In [32]:
# open the 'pkl' file you want to read
pkl_file = open('/Users/liyurun/Desktop/distance_data_20200613.pkl', 'rb')

# read the data
data = pickle.load(pkl_file)
pkl_file.close()

# data[何番目のドライバー][何回の配送][0,1,2,3]
##data[何番目のドライバー][何回の配送][0]  ###　今回配送のドライバーさんのコード
##data[何番目のドライバー][何回の配送][1]  ###　今回は何回目の配送
##data[何番目のドライバー][何回の配送][2]  ###　今回に配送された場所の経緯度
##data[何番目のドライバー][何回の配送][3]  ###　google mapsで得られた場所間の距離　i --> j 
例：data[0] １番目のドライバーさんの情報
　  data[0][0] １番目一回目の配送情報
   data[0][0][0] ドライバーさんのコード
   data[0][0][1] 一回目
   data[0][0][2]　配送場所経緯度
   data[0][0][3]　配送場所間の距離マトリックス
   data[0][0][3][i][j] 場所iから場所ｊまでのルート距離

In [50]:
#example 
data1[0]

[[24089,
  0,
  array([[ 35.1142283, 136.6409799],
         [ 35.1127311, 136.6390029],
         [ 35.1075064, 136.6350935],
         [ 35.1003225, 136.6348807]]),
  array([[   0,  343, 1851, 2326],
         [ 343,    0, 1539, 2014],
         [1851, 1539,    0, 2235],
         [2326, 2014, 2235,    0]])]]